- name: Install Nginx
  hosts: webservers
  become: true
  gather_facts: yes

  tasks:
    - name: Install Nginx on Debian-based systems
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == 'Debian'
      notify: 
        - Restart Nginx service

    - name: Install Nginx on Red Hat-based systems
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
      notify: 
        - Restart Nginx service

  handlers:
    - name: Restart Nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted